# Generated by Django 5.0.4 on 2024-04-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ratings', models.FloatField()),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('washing_capacity', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('maximum_spin_speed', models.IntegerField()),
                ('function_type', models.CharField(max_length=100)),
                ('inbuilt_heater', models.BooleanField(default=False)),
                ('washing_method', models.CharField(max_length=100)),
                ('product_url', models.URLField()),
            ],
        ),
    ]
